- name: Ensure httpd is not running
  ansible.builtin.service:
    name: httpd
    state: stopped

- name: Change http_port to 8080
  ansible.builtin.lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: ';?http_port = \d+'
    line: "http_port = 8080"
  notify: restart_grafana

- name: Adjust the theme to {{ grafana_theme }}
  ansible.builtin.lineinfile:
    path: /etc/grafana/grafana.ini
    regexp: ";?default_theme"
    line: "default_theme = {{ grafana_theme }}"
  notify: restart_grafana
